# Hugo Configuration
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/

# Website name
title: Xiaolei Ren
# Website URL
baseURL: 'https://xiaolei.ren/'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true

enableGitInfo: false
summaryLength: 30

pagination:
  pagerSize: 10

enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: ^
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]

permalinks:
  authors: '/author/:slug/'

disableAliases: true

outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart

timeout: 600000

taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types

markup:
  goldmark:
    renderHooks:
      link:
        useEmbedded: fallback
  highlight:
    lineNos: false
