main:
  - name: About
    url: /#about
    weight: 10

  - name: Highlights
    url: /#highlights
    weight: 20

  - name: Experience
    url: /#experience
    weight: 30

  - name: Research
    url: /#research
    weight: 40

  - name: Publications
    url: /#publications
    weight: 50

  - name: Teaching
    url: /#teaching
    weight: 60

  - name: Services
    url: /#services
    weight: 70

  - name: Awards
    url: /#awards
    weight: 80

  - name: Grants
    url: /#grants
    weight: 90

  - name: Contact
    url: /#contact
    weight: 100
