appearance:
  mode: system
  color: blue

defaultContentLanguage: en
defaultContentLanguageInSubdir: false
plugins_css: ["custom"]

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Macau University of Science and Technology'
    description: 'Xiaolei Ren is an Assistant Professor at MUST. His research covers software security, binary analysis, program analysis, and trustworthy AI.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Xiaolei Ren"

footer:
  copyright:
    notice: '© {year} Xiaolei Ren. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

features:
  favicon: true
  math:
    enable: false
  privacy_pack:
    enable: false
